/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mi_pizzeria;

import javax.swing.JOptionPane;

/**
 *
 * @author Alumnos
 */
public class pizza_menu extends javax.swing.JFrame {

    /**
     * Creates new form pizza_menu
     */
    public pizza_menu() {
        initComponents();
        masa.add(rb1);
        masa.add(rb2);
        masa.add(rb3);
        masa.add(rb4);
        salsa.add(rb5);
        salsa.add(rb6);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masa = new javax.swing.ButtonGroup();
        salsa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        queso = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cantidad = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        tamaño = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        cb11 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb7 = new javax.swing.JCheckBox();
        cb8 = new javax.swing.JCheckBox();
        cb9 = new javax.swing.JCheckBox();
        cb10 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        cb13 = new javax.swing.JCheckBox();
        cb14 = new javax.swing.JCheckBox();
        cb15 = new javax.swing.JCheckBox();
        cb16 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        price_box = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        pizza4 = new javax.swing.JLabel();
        pizza3 = new javax.swing.JLabel();
        pizza2 = new javax.swing.JLabel();
        pizza1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1375, 765));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(202, 15, 15));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("La Mia Pizza");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 20, 290, 64);

        jTextField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextField1.setText("...");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 90, 320, 30);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 50, 30);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setText("Direccion");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 130, 60, 30);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setText("C.P.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 130, 30, 30);

        jTextField2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextField2.setText("  :  ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 170, 110, 30);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setText("Fecha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 170, 40, 30);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setText("Hora");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 170, 50, 30);

        jTextField3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextField3.setText("...");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(390, 130, 70, 30);

        jTextField4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextField4.setText("  /  /");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 170, 140, 30);

        jTextField5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextField5.setText("...");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(140, 130, 210, 30);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tamaño de Pizza");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 230, 110, 20);

        queso.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        queso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Queso Normal", "Nuevo 100% Mozarella +$25", "Queso Parmesano +$25", "Queso Crema +$25", "Queso Cheddar +$25" }));
        queso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quesoActionPerformed(evt);
            }
        });
        getContentPane().add(queso);
        queso.setBounds(280, 310, 180, 22);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cantidad de Pizzas");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 500, 120, 20);

        cantidad.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cantidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad);
        cantidad.setBounds(350, 500, 100, 22);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setText("Masa");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 290, 60, 20);

        rb1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb1.setText("Masa Original");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(50, 310, 107, 25);

        rb2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb2.setText("Masa Crunchy");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(50, 330, 111, 25);

        rb3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb3.setText("Masa Double Decker +$40");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        getContentPane().add(rb3);
        rb3.setBounds(50, 350, 190, 25);

        rb4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb4.setText("Masa D4 +$100");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });
        getContentPane().add(rb4);
        rb4.setBounds(50, 370, 130, 25);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Queso");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 310, 50, 20);

        tamaño.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tamaño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Mediana", "Grande", "Familiar" }));
        tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamañoActionPerformed(evt);
            }
        });
        getContentPane().add(tamaño);
        tamaño.setBounds(180, 230, 110, 22);

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Salsa");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 430, 40, 20);

        rb5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb5.setText("Si");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });
        getContentPane().add(rb5);
        rb5.setBounds(120, 430, 37, 25);

        rb6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rb6.setText("No");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });
        getContentPane().add(rb6);
        rb6.setBounds(170, 430, 45, 25);

        jButton1.setBackground(new java.awt.Color(255, 42, 42));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jButton1.setText("Nuevo pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 600, 150, 30);

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ingredientes");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(580, 180, 80, 16);

        cb1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb1.setText("Carnes");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(500, 230, 67, 30);

        cb6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb6.setText("Carne Molida");
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });
        getContentPane().add(cb6);
        cb6.setBounds(500, 370, 105, 40);

        cb11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb11.setText("Chorizo");
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });
        getContentPane().add(cb11);
        cb11.setBounds(630, 290, 71, 30);

        cb4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb4.setText("Salami");
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });
        getContentPane().add(cb4);
        cb4.setBounds(500, 320, 65, 25);

        cb5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb5.setText("Pollo");
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });
        getContentPane().add(cb5);
        cb5.setBounds(500, 350, 55, 25);

        cb2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb2.setText("Aceitunas");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2);
        cb2.setBounds(500, 260, 83, 25);

        cb7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb7.setText("Cebolla");
        cb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb7ActionPerformed(evt);
            }
        });
        getContentPane().add(cb7);
        cb7.setBounds(500, 410, 71, 25);

        cb8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb8.setText("Jalapeño");
        cb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb8ActionPerformed(evt);
            }
        });
        getContentPane().add(cb8);
        cb8.setBounds(500, 440, 79, 30);

        cb9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb9.setText("Jamon");
        cb9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb9ActionPerformed(evt);
            }
        });
        getContentPane().add(cb9);
        cb9.setBounds(630, 230, 100, 25);

        cb10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb10.setText("Pepperoni");
        cb10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb10ActionPerformed(evt);
            }
        });
        getContentPane().add(cb10);
        cb10.setBounds(630, 260, 89, 25);

        cb3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb3.setText("Salchicha Italiana");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        getContentPane().add(cb3);
        cb3.setBounds(500, 290, 130, 25);

        cb12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb12.setText("Tocino");
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });
        getContentPane().add(cb12);
        cb12.setBounds(630, 320, 65, 25);

        cb13.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb13.setText("Champiñones");
        cb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb13ActionPerformed(evt);
            }
        });
        getContentPane().add(cb13);
        cb13.setBounds(630, 350, 103, 25);

        cb14.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb14.setText("Piña");
        cb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb14ActionPerformed(evt);
            }
        });
        getContentPane().add(cb14);
        cb14.setBounds(630, 380, 55, 25);

        cb15.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb15.setText("Pimiento");
        cb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb15ActionPerformed(evt);
            }
        });
        getContentPane().add(cb15);
        cb15.setBounds(630, 410, 77, 25);

        cb16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cb16.setText("Tomate");
        cb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb16ActionPerformed(evt);
            }
        });
        getContentPane().add(cb16);
        cb16.setBounds(630, 440, 73, 25);

        jButton2.setBackground(new java.awt.Color(69, 208, 77));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton2.setText("Comprar");
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 590, 130, 50);

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setText("Registro:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(130, 50, 80, 20);

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(29, 98, 218));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Precio");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(540, 510, 80, 30);

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("$");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(630, 510, 20, 30);

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(600, 510, 40, 0);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("3 ingredientes incluidos");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(550, 200, 150, 16);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Ingrediente adicional +$15");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(540, 210, 160, 16);

        price_box.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        price_box.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(price_box);
        price_box.setBounds(660, 500, 70, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mi_pizzeria/dinero.gif"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(420, 560, 100, 100);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mi_pizzeria/checklist.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(10, 560, 100, 100);

        size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(size);
        size.setBounds(310, 214, 120, 90);
        getContentPane().add(pizza4);
        pizza4.setBounds(740, 90, 600, 600);
        getContentPane().add(pizza3);
        pizza3.setBounds(740, 90, 600, 600);
        getContentPane().add(pizza2);
        pizza2.setBounds(740, 90, 600, 600);

        pizza1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pizza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mi_pizzeria/pizza.jpg"))); // NOI18N
        getContentPane().add(pizza1);
        pizza1.setBounds(740, 90, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int pfinal=0, precio_tamaño=0, precio_queso=0, precio_ingredientes=0, precio_masa=0, ingredientes3=0, fin=0;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        precio_tamaño=0;
        precio_queso=0;
        precio_ingredientes=0;
        precio_masa=0;
        ingredientes3=0;
        pfinal=precio_tamaño+precio_queso+precio_ingredientes+precio_masa;
        fin=0;
        size.setIcon(new javax.swing.ImageIcon());
        pizza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("pizza.jpg")));
        pizza2.setIcon(new javax.swing.ImageIcon());
        pizza3.setIcon(new javax.swing.ImageIcon());
        pizza4.setIcon(new javax.swing.ImageIcon());
        price_box.setText(Integer.toString(pfinal));
        masa.clearSelection();
        salsa.clearSelection();
        tamaño.setSelectedIndex(0);
        queso.setSelectedIndex(0);
        cantidad.setSelectedIndex(0);
        cb1.setSelected(false);
        cb2.setSelected(false);
        cb3.setSelected(false);
        cb4.setSelected(false);
        cb5.setSelected(false);
        cb6.setSelected(false);
        cb7.setSelected(false);
        cb8.setSelected(false);
        cb9.setSelected(false);
        cb10.setSelected(false);
        cb11.setSelected(false);
        cb12.setSelected(false);
        cb13.setSelected(false);
        cb14.setSelected(false);
        cb15.setSelected(false);
        cb16.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb14ActionPerformed
        if (cb14.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb14ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        pizza2.setIcon(new javax.swing.ImageIcon(getClass().getResource("tomato-sauce.png")));
    }//GEN-LAST:event_rb5ActionPerformed

    private void cb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb9ActionPerformed
        if (cb9.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb9ActionPerformed

    private void cb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb10ActionPerformed
        if (cb10.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb10ActionPerformed

    private void tamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamañoActionPerformed
        if(tamaño.getSelectedIndex()==0) {
            size.setIcon(new javax.swing.ImageIcon());
            precio_tamaño=0;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
        else if(tamaño.getSelectedIndex()==1) {
            size.setIcon(new javax.swing.ImageIcon(getClass().getResource("mediana.png")));
            precio_tamaño=180;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
        else if(tamaño.getSelectedIndex()==2) {
            size.setIcon(new javax.swing.ImageIcon(getClass().getResource("grande.png")));
            precio_tamaño=240;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
        else if(tamaño.getSelectedIndex()==3) {
            size.setIcon(new javax.swing.ImageIcon(getClass().getResource("familiar.png")));
            precio_tamaño=480;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
    }//GEN-LAST:event_tamañoActionPerformed

    private void quesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quesoActionPerformed
        if(queso.getSelectedIndex()==0) {
            pizza3.setIcon(new javax.swing.ImageIcon());
            precio_queso=0;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
        else if(queso.getSelectedIndex()==1) {
            pizza3.setIcon(new javax.swing.ImageIcon(getClass().getResource("cheese.png")));
            precio_queso=0;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
        else if(queso.getSelectedIndex()==2) {
            pizza3.setIcon(new javax.swing.ImageIcon(getClass().getResource("cheese.png")));
            precio_queso=25;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
        else if(queso.getSelectedIndex()==3) {
            pizza3.setIcon(new javax.swing.ImageIcon(getClass().getResource("cheese.png")));
            precio_queso=25;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
        else if(queso.getSelectedIndex()==4) {
            pizza3.setIcon(new javax.swing.ImageIcon(getClass().getResource("cheese.png")));
            precio_queso=25;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
        else if(queso.getSelectedIndex()==5) {
            pizza3.setIcon(new javax.swing.ImageIcon(getClass().getResource("cheese.png")));
            precio_queso=25;
            if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
    }//GEN-LAST:event_quesoActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        if(cantidad.getSelectedIndex()==0) {
            price_box.setText("0");
        }
        else if(cantidad.getSelectedIndex()==1){
            fin=pfinal*1;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==2){
            fin=pfinal*2;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==3){
            fin=pfinal*3;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==4){
            fin=pfinal*4;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==5){
            fin=pfinal*5;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==6){
            fin=pfinal*6;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==7){
            fin=pfinal*7;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==8){
            fin=pfinal*8;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==9){
            fin=pfinal*9;
            price_box.setText(Integer.toString(fin));
        }
        else if(cantidad.getSelectedIndex()==10){
            fin=pfinal*10;
            price_box.setText(Integer.toString(fin));
        }
    }//GEN-LAST:event_cantidadActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        if (cb1.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb1ActionPerformed
  
    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        if (cb2.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        if (cb3.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        if (cb4.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb4ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        if (cb5.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        if (cb6.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb7ActionPerformed
        if (cb7.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb7ActionPerformed

    private void cb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb8ActionPerformed
        if (cb8.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb8ActionPerformed

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
        if (cb11.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb11ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
        if (cb12.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb12ActionPerformed

    private void cb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb13ActionPerformed
        if (cb13.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb13ActionPerformed

    private void cb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb15ActionPerformed
        if (cb15.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb15ActionPerformed

    private void cb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb16ActionPerformed
        if (cb16.isSelected()){
        pizza4.setIcon(new javax.swing.ImageIcon(getClass().getResource("pepperoni.png")));
        precio_ingredientes+=15;
        ingredientes3=precio_ingredientes-45;
        if (ingredientes3>0){
        pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        }
        else{
        precio_ingredientes-=15;
        ingredientes3-=15;
        if (ingredientes3<0){
        pfinal=precio_tamaño+precio_queso+precio_masa;
        price_box.setText(Integer.toString(pfinal));
        }
        else{
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
        }
    }//GEN-LAST:event_cb16ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        if (rb1.isSelected()){
        pizza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("pizza-crust.png")));
        precio_masa=0;
        if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        if (rb3.isSelected()){
        pizza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("pizza-crust.png")));
        precio_masa=40;
        if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        if (rb2.isSelected()){
        pizza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("pizza-crust.png")));
        precio_masa=0;
        if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        if (rb4.isSelected()){
        pizza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("pizza-crust.png")));
        precio_masa=100;
        if (ingredientes3>0){
            pfinal=precio_tamaño+precio_queso+ingredientes3+precio_masa;
            price_box.setText(Integer.toString(pfinal));
        }
            else{
            pfinal=precio_tamaño+precio_queso+precio_masa;
            price_box.setText(Integer.toString(pfinal));   
            }
        }
    }//GEN-LAST:event_rb4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (fin==0){
        JOptionPane.showMessageDialog(null, "Su total a pagar es de: $ " + fin +"\nSeleccione el numero de pizzas.");
        }
        else{
        JOptionPane.showMessageDialog(null, "Su total a pagar es de: $ " + fin);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
        pizza2.setIcon(new javax.swing.ImageIcon());
    }//GEN-LAST:event_rb6ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizza_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizza_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizza_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizza_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pizza_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cantidad;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb10;
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb13;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb15;
    private javax.swing.JCheckBox cb16;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb7;
    private javax.swing.JCheckBox cb8;
    private javax.swing.JCheckBox cb9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.ButtonGroup masa;
    private javax.swing.JLabel pizza1;
    private javax.swing.JLabel pizza2;
    private javax.swing.JLabel pizza3;
    private javax.swing.JLabel pizza4;
    private javax.swing.JLabel price_box;
    private javax.swing.JComboBox queso;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.ButtonGroup salsa;
    private javax.swing.JLabel size;
    private javax.swing.JComboBox tamaño;
    // End of variables declaration//GEN-END:variables
}
